apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup-step
      image: alpine
      workingDir: $(workspaces.source.path)
      script: |
        echo "Cleaning workspace..."
        rm -rf *
