site_name: LifeSearch Documentation
site_description: LifeSearch project Technical Docs

theme:
  name: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

nav:
  - Home: index.md
  - User Guide: user_guide.md
  - API reference:
    - Data Module: api/data.md
    - Reports Module: api/reports.md
    - LifeSearch Main Module: api/lifesearch_main.md
    - Routes Module: api/routes.md
  - Scientific Formulas: formulas_lifesearch.md
  - Bibliography and Data Sources: sources.md
  - About: about.md

plugins:
  - search        # Adds search functionality
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true       # Show name of the module at the top
            show_source: true             # Link to source code
            members_order: source         # Order members by source order
            docstring_style: google       # Assume Google-style docstrings
            merge_init_into_class: true   # Doc __init__ docstrings into class docstrings
            show_bases: true              # Show base classes for classes
            show_signature_annotations: true # Show type annotations in signatures
