apiVersion: v1
kind: PersistentVolume
metadata:
  name: lifesearch-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/lifesearch-data
  persistentVolumeReclaimPolicy: Retain
