apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pytest
spec:
  params:
    - name: args
      type: string
      default: "--color=yes --cov=lifesearch --cov-report=term-missing"
  workspaces:
    - name: source
  steps:
    - name: run-pytest
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        echo "🔧 Installing project dependencies..."
        pip install --upgrade pip
        pip install -r requirements-dev.txt

        echo "Running pytest with args: $(params.args)"
        pytest $(params.args)
